### ISSUE TITLE
CFShow Faults When Built against -fsanitize=address

### ISSUE THREAD

**Issue by gerickson** [gerickson/opencflite#57]
In any invocation of `CFShow` the underlying implementation, `CFShowToFile` faults when built against `-fsanitize=address` as follows for _tests/date_test_, for example:

```
==235149==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000004aa7a0 bp 0x7ffd0b191ba0 sp 0x7ffd0b191318 T0)
==235149==The signal is caused by a READ memory access.
==235149==Hint: address points to the zero page.
    #0 0x4aa7a0 in __sanitizer::internal_strlen(char const*) (tests/.libs/date_test+0x4aa7a0)
    #1 0x439dd5 in printf_common(void*, char const*, __va_list_tag*) (tests/.libs/date_test+0x439dd5)
    #2 0x43bb8f in fprintf (tests/.libs/date_test+0x43bb8f)
    #3 0x7efc93b60194 in _CFShowToFile (.libs/libCoreFoundation.so.635+0x3fa194)
    #4 0x7efc93b5f0d7 in CFShow (.libs/libCoreFoundation.so.635+0x3f90d7)
    #5 0x4c600e in check_date_constructors (.libs/date_test+0x4c600e)
    #6 0x4c6a0a in main (.libs/date_test+0x4c6a0a)
    #7 0x7efc914320b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #8 0x41c35d in _start (.libs/date_test+0x41c35d)
```

**Comment by gerickson** [comment]
Closed with #59.
