### ISSUE TITLE
Address Leak in BundleExample When Built with '-fsanitize=address'

### ISSUE THREAD

**Issue by gerickson** [gerickson/opencflite#87]
When configured with `configure -C --with-icu=/usr --with-tz-includes=/home/gerickson/src/git/github.com/gerickson/opencflite/tmp-build/../tzcode2021a CFLAGS=-O0 -g -fsanitize=address -fno-omit-frame-pointer -fno-optimize-sibling-calls LDFLAGS=-O0 -g -fsanitize=address -fno-omit-frame-pointer -fno-optimize-sibling-calls CPPFLAGS=-O0 -g -fsanitize=address -fno-omit-frame-pointer -fno-optimize-sibling-calls`, the _BundleExample_ fails against the `make check` target with:

```
/bin/bash ../../libtool --mode execute   ./BundleExample "/tmp/tmp.CFBundleExample-ZNIKbXXy/usr/local/share/CoreServices"
1. Test Application Bundle:
Bundle identifier: (null)
Version: 0
Bundle location (as URL): file://localhost/home/gerickson/src/git/github.com/gerickson/opencflite/tmp-build-fsanitize-address/examples/BundleExample/.libs/
Main CFBundle Dictionary: <CFBasicHash 0x6060000009e0 [0x7f7e36038be0]>{type = mutable dict, count = 1,
entries =>
	2 : <CFString 0x7f7e3603b820 [0x7f7e36038be0]>{contents = "CFBundleExecutablePath"} = <CFString 0x60d000000040 [0x7f7e36038be0]>{contents = "/home/gerickson/src/git/github.com/gerickson/opencflite/tmp-build-fsanitize-address/examples/BundleExample/.libs/BundleExample"}
}
:
Development region: (null)
Support files directory URL: file://localhost/home/gerickson/src/git/github.com/gerickson/opencflite/tmp-build-fsanitize-address/examples/BundleExample/.libs/
Resources directory URL: file://localhost/home/gerickson/src/git/github.com/gerickson/opencflite/tmp-build-fsanitize-address/examples/BundleExample/.libs/
Private frameworks directory URL: Frameworks/ -- file://localhost/home/gerickson/src/git/github.com/gerickson/opencflite/tmp-build-fsanitize-address/examples/BundleExample/.libs/
Shared frameworks directory URL: SharedFrameworks/ -- file://localhost/home/gerickson/src/git/github.com/gerickson/opencflite/tmp-build-fsanitize-address/examples/BundleExample/.libs/
Shared support directory URL: SharedSupport/ -- file://localhost/home/gerickson/src/git/github.com/gerickson/opencflite/tmp-build-fsanitize-address/examples/BundleExample/.libs/
Built-in Plugins directory URL: PlugIns/ -- file://localhost/home/gerickson/src/git/github.com/gerickson/opencflite/tmp-build-fsanitize-address/examples/BundleExample/.libs/
CFBundleCopyBundleLocalizations(): No localizations present.
CFBundleCopyExecutableArchitectures(): No architectures defined.


2. CFLite Bundle:
CFLite path: file://localhost/tmp/tmp.CFBundleExample-ZNIKbXXy/usr/local/share/CoreServices
Bundle identifier: com.apple.CFLite
Version: 0
Bundle location (as URL): file://localhost/tmp/tmp.CFBundleExample-ZNIKbXXy/usr/local/share/CoreServices/
Main CFBundle Dictionary: <CFBasicHash 0x606000001b80 [0x7f7e36038be0]>{type = mutable dict, count = 12,
entries =>
	0 : <CFString 0x603000001450 [0x7f7e36038be0]>{contents = "CFBundleName"} = <CFString 0x6030000013f0 [0x7f7e36038be0]>{contents = "CFLite"}
	1 : <CFString 0x604000000b50 [0x7f7e36038be0]>{contents = "CFBundleIdentifier"} = <CFString 0x604000000b90 [0x7f7e36038be0]>{contents = "com.apple.CFLite"}
	2 : <CFString 0x604000000bd0 [0x7f7e36038be0]>{contents = "CFBundleInfoDictionaryVersion"} = <CFString 0x603000001420 [0x7f7e36038be0]>{contents = "6.0"}
	4 : <CFString 0x604000000cd0 [0x7f7e36038be0]>{contents = "CFBundleVersion"} = <CFString 0x604000000d10 [0x7f7e36038be0]>{contents = "$(CURRENT_PROJECT_VERSION)"}
	5 : <CFString 0x7f7e3603b760 [0x7f7e36038be0]>{contents = "CFBundleInfoPlistURL"} = <CFURL 0x606000001ac0 [0x7f7e36038be0]>{type = 15, string = Info.plist, encoding = 134217984
	base = <CFURL 0x606000001760 [0x7f7e36038be0]>{type = 15, string = file://localhost/tmp/tmp.CFBundleExample-ZNIKbXXy/usr/local/share/CoreServices/, encoding = 134217984, base = (null)}}
	6 : <CFString 0x604000000b10 [0x7f7e36038be0]>{contents = "CFBundleExecutable"} = <CFString 0x6030000013f0 [0x7f7e36038be0]>{contents = "CFLite"}
	7 : <CFString 0x7f7e3603b7e0 [0x7f7e36038be0]>{contents = "CFBundleNumericVersion"} = <CFNumber 0x603000001660 [0x7f7e36038be0]>{value = +0, type = kCFNumberSInt32Type}
	9 : <CFString 0x604000000d50 [0x7f7e36038be0]>{contents = "CarbonLazyValues"} = <CFBasicHash 0x606000001c40 [0x7f7e36038be0]>{type = mutable dict, count = 1,
entries =>
	3 : <CFString 0x604000000d90 [0x7f7e36038be0]>{contents = "CodeFragmentManager"} = <CFBasicHash 0x606000001be0 [0x7f7e36038be0]>{type = mutable dict, count = 1,
entries =>
	6 : <CFString 0x603000001540 [0x7f7e36038be0]>{contents = "CoreFoundation"} = <CFString 0x604000000dd0 [0x7f7e36038be0]>{contents = "CFMPriv_CoreFoundation"}
}

}

	14 : <CFString 0x604000000c90 [0x7f7e36038be0]>{contents = "CFBundleSignature"} = <CFString 0x603000001510 [0x7f7e36038be0]>{contents = "????"}
	15 : <CFString 0x604000000c10 [0x7f7e36038be0]>{contents = "CFBundlePackageType"} = <CFString 0x6030000014b0 [0x7f7e36038be0]>{contents = "FMWK"}
	20 : <CFString 0x604000000ad0 [0x7f7e36038be0]>{contents = "CFBundleDevelopmentRegion"} = <CFString 0x6030000013c0 [0x7f7e36038be0]>{contents = "en_US"}
	22 : <CFString 0x604000000c50 [0x7f7e36038be0]>{contents = "CFBundleShortVersionString"} = <CFString 0x6030000014e0 [0x7f7e36038be0]>{contents = "6.7.2"}
}
:
Development region: en_US
Support files directory URL: file://localhost/tmp/tmp.CFBundleExample-ZNIKbXXy/usr/local/share/CoreServices/
Resources directory URL: file://localhost/tmp/tmp.CFBundleExample-ZNIKbXXy/usr/local/share/CoreServices/
Private frameworks directory URL: Frameworks/ -- file://localhost/tmp/tmp.CFBundleExample-ZNIKbXXy/usr/local/share/CoreServices/
Shared frameworks directory URL: SharedFrameworks/ -- file://localhost/tmp/tmp.CFBundleExample-ZNIKbXXy/usr/local/share/CoreServices/
Shared support directory URL: SharedSupport/ -- file://localhost/tmp/tmp.CFBundleExample-ZNIKbXXy/usr/local/share/CoreServices/
Built-in Plugins directory URL: PlugIns/ -- file://localhost/tmp/tmp.CFBundleExample-ZNIKbXXy/usr/local/share/CoreServices/
Bundle Localizations: <CFArray 0x604000000f10 [0x7f7e36038be0]>{type = mutable-small, count = 1, values = (
	0 : <CFString 0x6030000013c0 [0x7f7e36038be0]>{contents = "en_US"}
)}
PREFERRED Bundle Localizations: <CFArray 0x604000000fd0 [0x7f7e36038be0]>{type = mutable-small, count = 1, values = (
	0 : <CFString 0x603000001930 [0x7f7e36038be0]>{contents = "en_US"}
)}
CFBundleCopyExecutableArchitectures(): No architectures defined.

=================================================================
==111406==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f7e36189bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f7e35e18ab4 in __CFAllocatorSystemAllocate ../CFBase.c:275
    #2 0x7f7e35e195ed in CFAllocatorAllocate ../CFBase.c:647
    #3 0x7f7e35f0ae9d in _CFRuntimeCreateInstance ../CFRuntime.c:322
    #4 0x7f7e35f83ef3 in _CFURLAlloc ../CFURL.c:1653
    #5 0x7f7e35f9154d in CFURLCreateWithFileSystemPathRelativeToBase ../CFURL.c:3925
    #6 0x560b8252810a in main ../../../examples/BundleExample/BundleExample.c:270
    #7 0x7f7e35ba60b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Indirect leak of 120 byte(s) in 1 object(s) allocated from:
    #0 0x7f7e36189bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f7e35e18ab4 in __CFAllocatorSystemAllocate ../CFBase.c:275
    #2 0x7f7e35e195ed in CFAllocatorAllocate ../CFBase.c:647
    #3 0x7f7e35f481c2 in __CFStrAllocateMutableContents ../CFString.c:396
    #4 0x7f7e35f49f99 in __CFStringChangeSizeMultiple ../CFString.c:854
    #5 0x7f7e35f4a37d in __CFStringChangeSize ../CFString.c:914
    #6 0x7f7e35f4f8bf in __CFStringReplace ../CFString.c:1806
    #7 0x7f7e35f5bc3a in CFStringAppend ../CFString.c:4072
    #8 0x7f7e35f8fea9 in _convertToURLRepresentation ../CFURL.c:3715
    #9 0x7f7e35f84217 in _CFURLInit ../CFURL.c:1690
    #10 0x7f7e35f9157f in CFURLCreateWithFileSystemPathRelativeToBase ../CFURL.c:3926
    #11 0x560b8252810a in main ../../../examples/BundleExample/BundleExample.c:270
    #12 0x7f7e35ba60b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f7e36189bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f7e35e18ab4 in __CFAllocatorSystemAllocate ../CFBase.c:275
    #2 0x7f7e35e195ed in CFAllocatorAllocate ../CFBase.c:647
    #3 0x7f7e35f0ae9d in _CFRuntimeCreateInstance ../CFRuntime.c:322
    #4 0x7f7e35f4faca in __CFStringCreateMutableFunnel ../CFString.c:1831
    #5 0x7f7e35f4fe34 in CFStringCreateMutable ../CFString.c:1866
    #6 0x7f7e35f8fe63 in _convertToURLRepresentation ../CFURL.c:3713
    #7 0x7f7e35f84217 in _CFURLInit ../CFURL.c:1690
    #8 0x7f7e35f9157f in CFURLCreateWithFileSystemPathRelativeToBase ../CFURL.c:3926
    #9 0x560b8252810a in main ../../../examples/BundleExample/BundleExample.c:270
    #10 0x7f7e35ba60b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7f7e36189bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f7e35e18ab4 in __CFAllocatorSystemAllocate ../CFBase.c:275
    #2 0x7f7e35e195ed in CFAllocatorAllocate ../CFBase.c:647
    #3 0x7f7e35f8ffba in _convertToURLRepresentation ../CFURL.c:3719
    #4 0x7f7e35f84217 in _CFURLInit ../CFURL.c:1690
    #5 0x7f7e35f9157f in CFURLCreateWithFileSystemPathRelativeToBase ../CFURL.c:3926
    #6 0x560b8252810a in main ../../../examples/BundleExample/BundleExample.c:270
    #7 0x7f7e35ba60b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: 296 byte(s) leaked in 4 allocation(s).
```

**Comment by gerickson** [comment]
Closed with #88.
